version: '3.7'
services:
  redisgraph:
    image: redislabs/redismod
    container_name: redisg
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - redisgn
    hostname: redis
  mappingserver:
    image: comp5530m-mapping-project/comp5530m_mapping_project/mapping-app:main
    container_name: mapping
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - redisgn
networks:
  redisgn:
