version: '3.7'
services:
  redis:
    image: redislabs/redismod
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis:/data
  mapping:
    depends_on: 
      - redis
    image: registry.gitlab.com/comp5530m-mapping-project/comp5530m_mapping_project/mapping-app:main
    ports:
      - "80:80"
    restart: unless-stopped
volumes:
  redis:
