[GLOBAL]
pants_version = "2.9.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.flake8",
  "pants.backend.experimental.docker",
  "pants.backend.experimental.docker.lint.hadolint",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  'server',
]

[python]
# Make sure we are building against 3.8 so docker can run it
interpreter_constraints = [">=3.8,<3.9"]

[docker]
build_args = ["BUILD_TAG"]

[docker.registries.gitlab]
address = "registry.gitlab.com/comp5530m-mapping-project/comp5530m_mapping_project"
default = true
