python_tests(
    name="tests",
    dependencies=["server/tests/parser/test_map/LineString.json", 
                  "server/tests/parser/test_map/Points.json", 
                  "server/tests/parser/test_map/Polygons.json"]
)
